markdown: redcarpet
highlighter: pygments
permalink: /blog/:title
include: ['.htaccess']
url: http://www.ericlagergren.com
name: Eric Lagergren
tagline: Eric Lagergren | CNE Politics Sports
description: Eric Lagergren's Blog Projects and Resume
production_url: www.ericlagergren.com
exclude: ['_site']
excerpt_separator: ""
paginate: 20
paginate_path: "/archives/page/:num"
gem:
  - jekyll-sitemap
